### ISSUE TITLE
USER STORY: Reset password

### ISSUE THREAD

**Issue by pavlo-myskov** [FlashDrag/agile-project-test#11]
Epic: #5 

### Description
As a user, I want to reset my password, so that I can access my account if I forget my password.

### Acceptance Criteria
- The user must be able to reset their password.
- The user must receive an email with a link to reset their password.
- The user must be able to change their password.

### Tasks
- [ ] - Create a reset password form.
- [ ] - Create a reset password email template.
- [ ] - Create a reset password email.
