### ISSUE TITLE
USER STORY: 2

### ISSUE THREAD

**Issue by pavlo-myskov** [FlashDrag/agile-project-test#3]
Epic: #1 

### Description
In order to provide anonymous feedback as a user, I can choose to hide my identity in the pool response.

### Acceptance Criteria
- The option should be provided as a checkbox
- The checkbox should be “checked” by default
- The option should appear next to the submit button
- After submitting the default submission confirmation should be adjusted to include the user name.

### Tasks
- [x] Update the view: the pool design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
