### ISSUE TITLE
USER STORY: Sign-in using username/password

### ISSUE THREAD

**Issue by pavlo-myskov** [FlashDrag/agile-project-test#6]
Epic: #5 

### Description
As a user, I want to be able to sign in to my acc using a username and password

### Tasks
- [ ] Design user interface
- [ ] Implement HTML and CSS
- [ ] Create the Models
